### ISSUE TITLE
Getting error running Advanced React Patterns on local

### ISSUE THREAD

**Issue by zkula** [epicweb-dev/advanced-react-patterns#100]
This error screen appears as soon as I click on any one of the lessons.

![image](https://user-images.githubusercontent.com/40850966/169666039-2e0d0eea-17ce-43ca-afd2-1c93535aa131.png)

**Comment by zkula** [comment]
Note: I have already tried re-rendering the app, as well as re-installing the entire Advanced-React-Patterns repo.

**Comment by kentcdodds** [comment]
Could you double-check your `package.json`? The scripts for `build`, `start`, and `test` should reference `craco`. If they are using `react-scripts` then change that to `craco` and it should work again.

**Comment by zkula** [comment]
That worked. Thank you very much!
