### ISSUE TITLE
Bug: unable to reproduce the `useLayoutEffect: auto-scrolling textarea` chapter

### ISSUE THREAD

**Issue by jynxio** [epicweb-dev/advanced-react-patterns#101]
## Chapter
useLayoutEffect: auto-scrolling textarea -> useLayoutEffect Solution

## Description
The author describes a situation in the video: Since `useEffect` is always executed after layout and paint, the UI may become torn.
The author then demonstrates this situation using the original code of `04.js`, specifically:
1. Click the `add message` button.
2. The message box adds a message immediately.
3. After a few moments, the information box is positioned to the position of the new information.

**The problem I'm having is that I can't reproduce the example.**

I found the reason from the React 18 Working Group: **In React 18, useEffect fires synchronously when it's the result of a discrete input.**

> You can find a more detailed description [here](https://github.com/reactwg/react-18/discussions/128).

I would like to give the author feedback on this matter, which is the purpose of this issue.

**Comment by kentcdodds** [comment]
Hi @jynxio! 

I think you meant to post this on the [Advanced React Hooks workshop](https://github.com/kentcdodds/advanced-react-hooks). You'll notice that this change is noted in the notes of that exercise: https://github.com/kentcdodds/advanced-react-hooks/blob/main/src/exercise/04.md#exercise

Thanks!
