### ISSUE TITLE
`initialOn` and `reducer` props not passed from Toggle component to useToggle hook for exercise 6

### ISSUE THREAD

**Issue by kenneth-gray** [epicweb-dev/advanced-react-patterns#110]
When going through this exercise I figured I'd follow the warning advice and use `initialOn` to test my changes. That's how I came across that it wasn't working as expected. I also noticed the `reducer` prop also wasn't being passed through.

I reckon passing through `initialOn` is worth changing given it's related to the warning message being printed; `reducer` not so much. Thoughts?

**Comment by kentcdodds** [comment]
I suppose we could accept it as a prop to the Toggle component and forward it along to the useToggle hook even though it's not used. Same for reducer. I've just pushed that improvement and added you to the contributors table :) Thanks!
