### ISSUE TITLE
Playwright tests assume app is running on port 3000

### ISSUE THREAD

**Issue by danvoyce** [epicweb-dev/advanced-react-patterns#111]
I ran `npm run validate` whilst having another app running on port 3000, therefor causing all the tests to timeout / fail:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/1253802/220447233-ec39e0d9-050a-48eb-8bab-77815e52a539.png">

Would be nice to somehow pass the port number to tests somehow 🤔

**Comment by kentcdodds** [comment]
Thanks for reporting this. You can pass the port by running the tests with `PORT=3001 npm test`. Unfortunately there's no way for us to detect which port you're running the actual app on.

**Comment by danvoyce** [comment]
Hey I was thinking about this, and maybe it would make more sense to simply change the port to something less popular in order to reduce the chances of a conflict? When this happened to me it wasn't immediately obvious what the cause was, so likely this will trip someone else up at some point.

Happy to open a PR if you don't see any issues with that?

**Comment by kentcdodds** [comment]
Hey Dan. I'll give that thought. I'm still very actively developing the workshop app so I'll make that change myself if that's what I decide to do. Thanks!
