### ISSUE TITLE
Opinion on compound components with default children

### ISSUE THREAD

**Issue by hazem3500** [epicweb-dev/advanced-react-patterns#14]
In excerise 03 the Toggle component takes children 
```js
function Toggle({children}) {
  const [on, setOn] = React.useState(false)
  const toggle = () => setOn(!on)

  return (
    <ToggleContext.Provider value={{on, toggle}}>
      {children}
    </ToggleContext.Provider>
  )
}
```
but what if it took default children 
```js
function Toggle({ children }) {
  const [on, setOn] = React.useState(false);
  const toggle = () => setOn(!on);

  return (
    <ToggleContext.Provider value={{ on, toggle }}>
      {children || (
        <>
          <ToggleOn>The button is on</ToggleOn>
          <ToggleOff>The button is off</ToggleOff>
          <ToggleButton />
        </>
      )}
    </ToggleContext.Provider>
  );
}
```
and now you can use it like this

```js
    <div>
      {/* default children */}
      <Toggle />

      {/* OR */}

      {/* explicit children */}
      <Toggle>
        <ToggleOn>This button is on</ToggleOn>
        <ToggleOff>This button is off</ToggleOff>
        <ToggleButton />
      </Toggle>
    </div>
```

what are your opinion on giving default children? could this lead to any problems?

**Comment by hazem3500** [comment]
here is a codesandbox link if you want to try it out: https://codesandbox.io/s/still-firefly-6ulel?fontsize=14&hidenavigation=1&theme=dark

**Comment by kentcdodds** [comment]
If there's a common enough case for that then sure, but I can't imagine it being common enough in practice.

Thanks for the issue.

**Comment by hazem3500** [comment]
I think the use case for it is the type of component that 9 out of 10 of the times you'll want to use it as it is but in specific places you want to tweak it a bit, this way it lets you use the component without worrying about its internals but when needed you can expose whats inside the component.

what other pattern would you recommend that can handle that use case?

**Comment by kentcdodds** [comment]
Composition.

```javascript
function Toggle({children}) {
  const [on, setOn] = React.useState(false)
  const toggle = () => setOn(!on)

  return (
    <ToggleContext.Provider value={{on, toggle}}>
      {children}
    </ToggleContext.Provider>
  )
}

function DefaultToggle() {
  return (
    <Toggle>
      <ToggleOn>The button is on</ToggleOn>
      <ToggleOff>The button is off</ToggleOff>
      <ToggleButton />
    </Toggle>
  )
}
```

Then if the default works for you great, otherwise use the Toggle component itself.

**Comment by hazem3500** [comment]
Composition does sound like a better option, but where do you think the composed or default components should live? should the Toggle component export the DefaultToggle or should we consider the composed component as a different entity and create it as a separate component?

I think if the composed component is only composing the default usecase then putting it in the same place as the original component might be better since they are directly correlated and we will avoid bloating the components folder by not adding another component, But if the composed component did add more functionality or is composing more than one component then we can make it in its own component file.

what do you think?

**Comment by kentcdodds** [comment]
It just really depends on the specific scenario 🤷‍♂️
