### ISSUE TITLE
Unnecessary prop for Toggle in exercise 3 

### ISSUE THREAD

**Issue by Suhas010** [epicweb-dev/advanced-react-patterns#67]
There is an unused prop on the Toggle component in exercise 3.
<img width="481" alt="Screenshot 2021-04-03 at 12 33 42 PM" src="https://user-images.githubusercontent.com/8597576/113471241-d6765e00-9478-11eb-8dc8-2b4d22fc5cfb.png">

**Comment by kentcdodds** [comment]
Thanks!
