### ISSUE TITLE
Official Site?

### ISSUE THREAD

**Issue by abmagil** [epicweb-dev/advanced-react-patterns#73]
Is [this](https://advanced-react-patterns.netlify.app/) the official site for this repo or is it an infringement? I'm signed up for Epic React and the content looks extremely similar but the name seems to come from here.

I'm looking for a good place to link the Prop Getter pattern and I don't want to peddle in imposters.

**Comment by kentcdodds** [comment]
Hi @abmagil!

That site is the deployed version of this repo which can be useful for reference.

This repo is the official repository for the https://EpicReact.dev material and it's open source :)
