### ISSUE TITLE
Design pattern for switching product list layout

### ISSUE THREAD

**Issue by crisfcodes** [epicweb-dev/advanced-react-patterns#74]
Kent I'm taking ur React course and I'm here in this specific section about patterns, I want to apply the knowledge adquired refactorimg this **product list** which should render diferent layouts:
 - `stacked vertically (default)`
 - `horizontal (scroll)`
 - `grid`

The idea is to use the same component(s) to support all formats(DRY), here the layouts that I want to implement. 

### ProductList

Responsible for rendering a list of products. This component decide how to be rederized the list, in `vertical (default)`, `horizontal (scroll)`, or `grid` mode. 

```javascript
// ProductList.js

import React from 'react'
import {Dimensions, FlatList, View} from 'react-native'

// I'm using typescript, for the purpose of simplicity I don't put all the types
// in the code. Only the ones that define what each property of the component does.
export type ProductListProps = {
  /**
   * Products to display in the list
   */
  products: Product[]
  /**
   * If true, renders items next to each other horizontally instead of stacked
   * vertically.
   */
  showHorizontalList?: boolean
  /**
   * Tell how many columns in Grid.
   */
  numColumns?: number
  /**
   * If true, renders product list item content as column
   */
  productContentAsColumn?: boolean
}

function ProductList({
  products,
  numColumns = 1, 
  showHorizontalList = false,
}) {
  const getLayoutManager = () => {
    const layoutManager = {}
    if (showHorizontalList) {
      layoutManager.horizontal = true
      layoutManager.showsHorizontalScrollIndicator = false
      layoutManager.ItemSeparatorComponent = ProductListItemSeparator
      layoutManager.contentContainerStyle = {padding: 16}
    } else {
      layoutManager.numColumns = numColumns
    }

    return layoutManager
  }

  const renderItemRow = ({item}) => (
    <ProductListItem
      product={item}
      viewContainerStyle={{
        width: Dimensions.get('window').width / numColumns,
      }}
      // change item content direaction from `row` to 'column'
      columnContainerStyle={{flexDirection: 'column'}}
    />
  )

  return (
    <FlatList
      {...getLayoutManager()}
      // Pass a changing value to the `key` prop to update the columns number on the fly
      key={numColumns}
      data={products}
      renderItem={renderItemRow}
    />
  )
}
```

### ProductListItem

Responsible for rendering list's _item_ content. From here, you can modify the `itemContainerStyle` to decide how much space each item should occupy or `contentContainerStyle` to decide whether it should be rendered as a `row(default)` or `column(card)`.

```javascript
// ProductListItem.js

import {View} from 'react-native'

export type ProductListItemProps = {
  /**
   * Product to display
   */
  product: FeaturedProduct
  /**
   * With this styles you can definde the space can be filled by each item in the list
   */
  itemContainerStyle?: StyleProp<ViewStyle>
  /**
   * With this styles you can define if item content should render as `row` or `column`
   */
  itemContentStyle?: StyleProp<ViewStyle>
}

function ProductListItem({
  product,
  itemContainerStyle = {},
  itemContentStyle = {},
}) {
  return (
    <View style={itemContainerStyle}>
      <View style={[styles.row, itemContentStyle]}>
        // any content can be placed here
      </View>
    </View>
  )
}

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
  },
})
```

## Problem

This nested component design can be really messy(creating ProducListItem inside ProducList). I would like to know if a specific react design pattern can be applied in this case to decouple list(parent) to items(childs), taking into account that the children must access the parent's state/props in order to know what kind of layout should be rendered. I'm think that Compound Components can fit here but I'm not sure, any advice in what design pattern can I use here.

**Comment by kentcdodds** [comment]
Hi @crisfcodes, would you mind bringing this to my [office hours](https://kcd.im/office-hours) so I can give your question the attention it needs? :)

**Comment by crisfcodes** [comment]
Of course @kentcdodds thanks

**Comment by kentcdodds** [comment]
I've got a new pattern in the `next` branch called Composition and Layout Components that *might* help with this a little bit. Either way I'm pretty solid on the next version of this workshop so I'm going to close this. Thanks!
