### ISSUE TITLE
One-liner summary on top

### ISSUE THREAD

**Issue by Aprillion** [epicweb-dev/advanced-react-patterns#76]
As discussed on https://discord.com/channels/715220730605731931/759594637496811520/871062940487417866, it would be nice to have a 1-liner summary on top of each pattern, even before the Background, to make it easier for us to re-visit the patterns and trigger our memory.

**Comment by bybrunobarros** [comment]
If we consider these patterns as design patterns (a reusable solution to a commonly occurring problem within a given context) we should remind what triggers the pattern (the kind of problem the pattern is solving).

**Comment by kentcdodds** [comment]
I do try to do all this within the background and exercise sections, but I think a quick summary at the top of the background would be helpful, especially to trigger memory 👍 I'll make sure to add that in an update 👍
