### ISSUE TITLE
Exercise 2, Advanced React Patterns - Unclear explanation

### ISSUE THREAD

**Issue by caseykhuc** [epicweb-dev/advanced-react-patterns#87]
In exercise 2, workshop Advanced React Patterns, I understand how to implement the pattern but don't quite get the problem it solves.

Quoting:
```
We have a Toggle component that manages the state, and we want to render different parts of the UI however we want. We want control over the presentation of the UI.

🦉 The fundamental challenge you face with an API like this is the state shared between the components is implicit, meaning that the developer using your component cannot actually see or interact with the state (on) or the mechanisms for updating that state (toggle) that are being shared between the components.

So in this exercise, we’ll solve that problem by providing the compound components with the props they need implicitly using React.cloneElement.

```

So what is `an API like this` ? Because the example is not complete / working yet.
And basically the passing state from parent to children is still implicit after the pattern is applied. So what is the problem it solves here? Thanks!

**Comment by kentcdodds** [comment]
Could you bring this question to my office hours? https://kcd.im/office-hours
