### ISSUE TITLE
node setup fails with node 17

### ISSUE THREAD

**Issue by danrot** [epicweb-dev/advanced-react-patterns#93]
Although the Readme states that node 17 should be working, the `node setup` command fails for me with the following message:

```
▶️  Starting workshop setup...
      Running the following command: npx "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
    ▶️  Starting: System Validation
          Ensuring the correct versions of tools are installed on this computer.
          Running the following command: npx "https://gist.github.com/kentcdodds/abbc32701f78fa70298d444c2303b6d9"
There were errors validating the compatibility of this computer:

    This computer has node@v17.3.0 installed, but node@12 || 14 || 15 || 16 is required. Please update node: https://nodejs.org


If you would like to just ignore this error, then feel free to do so and install dependencies as you normally would in "/Users/roda/Documents/Development/advanced-react-patterns". Just know that things may not work properly if you do...
    🚨  Failure: System Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.
```

**Comment by kentcdodds** [comment]
The README needs to be updated. There are issues with node 17. Thanks for opening the issue. I'll fix the README.

**Comment by kentcdodds** [comment]
Oh, also make sure you're on the `next` branch when you run the setup as the emailed instructions indicated (the README is correct in that branch. I'm correcting the `main` branch now).

**Comment by danrot** [comment]
Are there any serious issues with node 17 that prevent me from participating? Have no other node version installed right now on the machine I plan to participate with and sit in the bus right now. npm install and the other commands worked, just node setup did not.

**Comment by kentcdodds** [comment]
I'd it works that's great, but some have experienced issues
