### ISSUE TITLE
Workshop Setup: no `config/tsconfig.exercise.json` file

### ISSUE THREAD

**Issue by zladuric** [epicweb-dev/advanced-react-patterns#94]
There's no `config/tsconfig.exercise.json` file, even though the Readme is suggesting editing it.

I'm preparing for today's workshop, and the readme [here in the "TypeScript" part](https://github.com/kentcdodds/advanced-react-patterns/blob/next/README.md#typescript) suggests that, to enable the TS Strict mode, one should configure it in `config/tsconfig.exercise.json` file. However, there is no such file, nor `config/` directory. I am not certain if it's worth the effort, but I think either rewording this ("create config/tsconfig...") or creating a placeholder tsconfig file there should help with first-time setup of the repo.

**Comment by kentcdodds** [comment]
Make sure you're in the `next` branch as the email instructions indicated

**Comment by zladuric** [comment]
Yep, I'm on the `next` branch. No `config` directory.

```bash
$ find . -iname "tsconfig*" -not -path "./node_modules/*"
./tsconfig.json
$ git branch -vv
  main 2aafe98 [origin/main] use npm@6
* next 28e27c5 [origin/next: ahead 1] email autofill
$
```

**Comment by kentcdodds** [comment]
I'll look into it...

While I have you here, do you happen to know why nobody has joined the zoom meeting yet even though I believe it was supposed to start 4 minutes ago? Is my calendar event off?

**Comment by kentcdodds** [comment]
The fix for this is simple but it'd be more work than it's worth for everyone involved so I won't fix this until after our workshop. Feel free to adjust the tsconfig settings in the regular tsconfig.json file as you'd prefer.

**Comment by zladuric** [comment]
@kentcdodds by my calendar, we're starting in 40 minutes (4pm Munich time) - that's what it says in my invitation.

**Comment by kentcdodds** [comment]
I should have asked Daniel to send me your invitation 😅

Thanks! See you in 35 minutes :)

Also, I decided to push the fix, so if you'd like to redo the setup you're welcome to. Should work fine either way though. Cheers!
