### ISSUE TITLE
process is not defined error. Interactivity blocked

### ISSUE THREAD

**Issue by vmerino** [epicweb-dev/advanced-react-patterns#95]
Hello!

I started running into this `process is not defined` error yesterday.  I did not run into this same error in any of the previous modules.  It's happening after every hot-reload.  

![image](https://user-images.githubusercontent.com/5444971/152024825-bed27f78-77eb-4c80-83d3-a91992c09e9a.png)

After a bit of googling, I found this create-react-app issue: https://github.com/facebook/create-react-app/issues/11773.  Looks like the same issue?

Here's my setup: 

![image](https://user-images.githubusercontent.com/5444971/152025562-a9a9996b-6006-4ea8-8d03-3e1089a863b1.png)

Steps to Repro: 
1. Clone repo
2. Run setup and start project as per readme.
4. Trigger a hot reload by making any change to code & save. 

Error will appear in console.  It's happening on every page, including the isolated pages.

Once the error is triggered, I am unable to interact with the page.  Buttons don't work and scrolling is disabled.  This might be due to an iframe that blocks everything.  This was also mentioned in the issue referenced above.

Here's the iframe I am seeing appear after the error is triggered:
![image](https://user-images.githubusercontent.com/5444971/152027562-4c0fc281-4f53-4a86-a06e-382b6ff26c96.png)

Let me know if you need anything else from my end.

Thanks!

**Comment by kentcdodds** [comment]
Hi @vmerino,

I just pushed an update. Do you mind cloning and running the setup script again to see whether it fixed this issue?

**Comment by vmerino** [comment]
Hey @kentcdodds looks like that worked! I am no longer able to repro.  Thank you!

**Comment by kentcdodds** [comment]
Good news! Thanks :)
