### ISSUE TITLE
Async/Await `updateUser(dispatch, user, updates)` fails `failure works` test in exercise `1`

### ISSUE THREAD

**Issue by ghost** [epicweb-dev/advanced-react-patterns#96]
```js
async function updateUser(dispatch, user, updates) {
  dispatch({type: 'start update', updates})
  try {
    const updatedUser = await userClient.updateUser(user, updates)
    dispatch({type: 'finish update', updatedUser})
    return updatedUser
  } catch (error) {
    dispatch({type: 'fail update', error})
    throw error
  }
}
```
<img width="383" alt="image" src="https://user-images.githubusercontent.com/1727278/152678120-5c671831-f300-4e07-9b47-9cbfedf13712.png">

**Comment by ghost** [comment]
And this one, works fine
```js
function updateUser(dispatch, user, updates) {
  dispatch({ type: 'start update', updates })
  return userClient.updateUser(user, updates).then(
    updatedUser => dispatch({ type: 'finish update', updatedUser }),
    error => dispatch({ type: 'fail update', error }),
  )
}
```
<img width="401" alt="image" src="https://user-images.githubusercontent.com/1727278/152678195-4a57c6f4-78ca-4748-8007-21703aaa9b82.png">

**Comment by kentcdodds** [comment]
Make sure that your version has the empty `catch` block: https://github.com/kentcdodds/advanced-react-patterns/blob/7770682631c8aa2414a06cb65c2bdc7f97766d10/src/final/01.js#L111
