### ISSUE TITLE
Element type is invalid error upon starting the app

### ISSUE THREAD

**Issue by ubrandrew** [epicweb-dev/advanced-react-patterns#99]
I'm seeing the following error after running `npm start`: `Element type is invalid. Received a promise that resolves to: /static/media/01.5905cfaa607076924a2c.md. Lazy element type must resolve to a class or function.`
Validation is passing as well.

Heres the stack trace im seeing in the console:
```
react-dom.production.min.js:186 Error: Minified React error #306; visit https://reactjs.org/docs/error-decoder.html?invariant=306&args[]=%2Fstatic%2Fmedia%2F01.5905cfaa607076924a2c.md&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ws (main.e273faf5.js:2:260313)
    at gu (main.e273faf5.js:2:248394)
    at vu (main.e273faf5.js:2:248322)
    at mu (main.e273faf5.js:2:248185)
    at au (main.e273faf5.js:2:244969)
    at ru (main.e273faf5.js:2:243520)
    at k (main.e273faf5.js:2:291290)
    at MessagePort.P (main.e273faf5.js:2:291824)
```
Both rerendering and reloading do not fix the issue 

![Screen Shot 2022-05-20 at 10 44 34 AM](https://user-images.githubusercontent.com/36085577/169553529-bc5a9e74-9bf4-4ee3-94ab-a7b518a3f3f0.png)

**Comment by kentcdodds** [comment]
Sorry for the trouble. This has been fixed. Please update your repo. Thanks!
